version: "3.9"

services:
  db:
    image: postgres:16
    container_name: bank_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: aaaa1234
      POSTGRES_DB: bankdb
    ports:
      - "6000:5432" # 外部 6000 對應容器內部 5432
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
  app:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:8080"
    depends_on:
      - db
  db-test:
    image: postgres:16
    container_name: pg-test
    profiles: [ "test" ] # 設定此服務僅在 test profile 下啟動
    ports:
      - "6001:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: testDB
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db-data:
