basePath: /
definitions:
  domain.Account:
    properties:
      balance:
        type: number
      id:
        type: string
      name:
        type: string
    type: object
  request.CreateAccountRequest:
    properties:
      balance:
        type: number
      name:
        type: string
    type: object
  request.TransactionRequest:
    properties:
      amount:
        type: number
    type: object
host: localhost:8080
info:
  contact: {}
  description: A simple banking system implemented in Go (with standard library ServeMux)
  title: Simple Bank System API
  version: "1.0"
paths:
  /accounts:
    post:
      consumes:
      - application/json
      description: 建立一個新的帳號，初始餘額必須 >= 0
      parameters:
      - description: Account Info
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/request.CreateAccountRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Account'
      summary: 建立帳號
      tags:
      - accounts
  /accounts/{id}:
    get:
      consumes:
      - application/json
      description: 根據帳號 ID 查詢帳號資訊
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Account'
      summary: 查詢帳號
      tags:
      - accounts
  /accounts/{id}/transactions:
    post:
      consumes:
      - application/json
      description: 對指定帳號進行存款或提款操作，金額為正數表示存款，負數表示提款
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      - description: Transaction Info
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/request.TransactionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Account'
      summary: 進行交易
      tags:
      - transactions
  /accounts/transfer:
    put:
      consumes:
      - application/json
      description: 由指定帳號進行轉帳操作
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      - description: Transaction Info
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/request.TransactionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Account'
      summary: 進行轉帳
      tags:
      - transactions
swagger: "2.0"
