basePath: /
definitions:
  request.CreateAccountRequest:
    properties:
      balance:
        type: number
      name:
        type: string
    type: object
  request.TransactionRequest:
    properties:
      amount:
        type: number
    type: object
  request.TransferRequest:
    properties:
      amount:
        type: number
      from_id:
        type: string
      to_id:
        type: string
    type: object
  response.ApiResponse:
    properties:
      data: {}
      error:
        type: string
      status:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: A simple banking system implemented in Go with RESTful APIs.
  title: Simple Bank System API
  version: "1.0"
paths:
  /accounts:
    post:
      consumes:
      - application/json
      description: 建立一個新的帳號，初始餘額必須 >= 0
      parameters:
      - description: Account Info
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/request.CreateAccountRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ApiResponse'
      summary: 建立帳號
      tags:
      - 帳號相關
  /accounts/{id}:
    get:
      consumes:
      - application/json
      description: 根據帳號 ID 查詢帳號資訊
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ApiResponse'
      summary: 查詢帳號
      tags:
      - 帳號相關
  /accounts/{id}/transactions:
    get:
      consumes:
      - application/json
      description: 取得指定交易的詳細資訊
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ApiResponse'
      summary: 取得交易紀錄
      tags:
      - 交易相關
    post:
      consumes:
      - application/json
      description: 對指定帳號進行存款或提款操作，金額為正數表示存款，負數表示提款
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      - description: Transaction Info
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/request.TransactionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ApiResponse'
      summary: 交易
      tags:
      - 交易相關
  /accounts/transfer:
    post:
      consumes:
      - application/json
      description: 由指定帳號進行轉帳操作
      parameters:
      - description: Transfer Info
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/request.TransferRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ApiResponse'
      summary: 轉帳
      tags:
      - 交易相關
swagger: "2.0"
